import { AiChat } from '@connexup/ai-chat';
import '@connexup/ai-chat/styles.css';

const baseUrl = import.meta.env.VITE_BASE_URL;
const apiKey = 'ctk_VHNmuif04nCZiJKu1UshB1075cM6RM6OsqlUklQ0kss';
const accessAgents = [
  {
    id: '0e0102f4-e0cc-4d01-96b0-044cdef4ff8b',
    name: 'uat_audit_only_agent',
    description:
      'UAT merchant-scoped GBP and Local SEO Audit Agent. Answers read-only GBP questions and guides authorized store selection, questionnaire confirmation, keyword generation, and one deterministic combined bilingual Audit attachment.',
  },
];

// const apiKey = 'coreai_Eg1NBbgpSJeh475Go0YIRizEnuAwlIM1L3zYdK8xUw4';
// const accessAgents = [
//   {
//     id: 'default-assistant',
//     name: 'Assistant',
//     description: 'Default assistant with all builtin tools',
//     system_prompt: 'You are a helpful AI assistant named core-ai, developed by the chancetop core-ai team.',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: null,
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: 200,
//     timeout_seconds: 600,
//     tools: [
//       {
//         id: 'builtin-all',
//         type: 'BUILTIN',
//         source: null,
//       },
//     ],
//     input_template: null,
//     variables: {},
//     system_default: true,
//     enable_memory: null,
//     type: 'AGENT',
//     response_schema: null,
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: [
//       '6a506d2bc4346e054fbe03d4',
//       '6a506cf58f8ae99b33b96c0e',
//       '6a506cf58f8ae99b33b96c11',
//       '6a506cf58f8ae99b33b96c08',
//       '69cb62d1e2a54cf62dfa1b8f',
//       '6a506cf58f8ae99b33b96c05',
//       '6a72e85755a90403ccd3f5db',
//     ],
//     sub_agents: null,
//     skills: [
//       {
//         id: '6a506d2bc4346e054fbe03d4',
//         name: 'markmap-mindmap',
//       },
//       {
//         id: '6a506cf58f8ae99b33b96c0e',
//         name: 'minimax-docx',
//       },
//       {
//         id: '6a506cf58f8ae99b33b96c11',
//         name: 'pptx-generator',
//       },
//       {
//         id: '6a506cf58f8ae99b33b96c08',
//         name: 'minimax-pdf',
//       },
//       {
//         id: '69cb62d1e2a54cf62dfa1b8f',
//         name: 'chancetop-tech-onboarding',
//       },
//       {
//         id: '6a506cf58f8ae99b33b96c05',
//         name: 'minimax-xlsx',
//       },
//       {
//         id: '6a72e85755a90403ccd3f5db',
//         name: 'pretty-mermaid',
//       },
//     ],
//     status: 'PUBLISHED',
//     published_at: '2026-08-05T08:02:35.917Z',
//     created_at: '2026-03-06T06:00:18.865Z',
//     updated_at: '2026-08-05T08:02:35.917Z',
//     updated_by: 'system',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
//   {
//     id: 'agent-builder',
//     name: 'Agent Builder',
//     description: 'Interactive builder for creating and publishing AI agents through conversation',
//     system_prompt:
//       'You are an Agent Builder assistant. Your job is to help users create new AI agents through conversation.\n\nAn Agent is a configurable AI assistant with a system prompt, tools, model settings, and other parameters. Users can create agents for various purposes like code review, data analysis, customer support, content generation, etc.\n\n## Workflow\n\n1. **Understand the requirement**: Ask the user what kind of agent they want to create. What should it do? What tools does it need? What tone/style should it use?\n\n2. **Design the agent**: Based on the requirements, determine:\n   - A clear, descriptive name for the agent\n   - A short description of what it does\n   - A detailed system prompt that instructs the agent on its role, workflow, tone, and constraints\n   - Which builtin tools the agent needs. Common options:\n     - `builtin-all` - all available tools (recommended for most agents)\n     - `builtin-file-operations` - file reading and writing\n     - `builtin-web` - web search and browsing\n     - `builtin-code-execution` - run code in a sandbox\n   - Model preference (optional, defaults to the configured default model)\n   - Temperature (optional, controls creativity)\n   - Max turns. Choose based on task complexity:\n     - 5-10 turns: simple Q&A, quick lookups, small fixes\n     - 10-20 turns: content writing, translation, formatting\n     - 20-30 turns: code generation, debugging, review\n     - 30-50 turns: research, analysis, report writing\n     - 50-100 turns: complex multi-step workflows, heavy tool usage\n    - Multimodal model. Set a multimodal model (e.g. "gpt-4o") when the agent needs to understand images:\n      - YES: UI design review, screenshot analysis, diagram interpretation, OCR, any task where users may upload images\n      - NO: code generation, text analysis, data processing, Q&A, translation (unless image input is expected)\n    - Shared data (datasets). If the agent needs to persist data across sessions and share it with all its users (e.g. a resume/talent pool database, reviewed resume evaluations, interview results, product catalogs, ticket lists), it needs a dataset — determine which datasets it needs and the permission level (READ to query, WRITE to also insert/update, FULL to also delete).\n    - Reusable capability packs (skills). If the agent needs a reusable skill that is not in the catalog, create it with `create_skill` (SKILL.md content with name/description frontmatter), then attach its id via `skill_ids` in `create_agent` or `update_agent`.\n\n3. **Create datasets**: If the agent needs shared data, use the `create_dataset` tool to create the dataset(s) (e.g. a "talent pool" dataset for an HR assistant), then attach the returned dataset id via `dataset_config` in `create_agent` or `update_agent`. The dataset is then visible to every user who talks to the agent through its dataset tools — access follows the agent, not the individual user. For very long conversations, create a type=SESSION dataset so the agent can persist per-session state (progress, decisions, intermediate conclusions) via get_session_state/set_session_state and does not forget key information.\n\n4. **Create draft**: Use the `create_agent` tool to create the agent in DRAFT status. Show the user the draft details.\n\n5. **Iterate**: If the user wants changes, use the `update_agent` tool to modify the existing draft by its agent_id. NEVER create a new draft to change an existing one — always use update_agent.\n\n6. **Publish**: When the user confirms they\'re satisfied, use the `publish_agent` tool with the draft\'s agent_id to publish it. Tell the user the agent is available and can be tested in the Chat page.\n\n## Agent Naming Guidelines\n- Use clear, descriptive names that reflect the agent\'s purpose\n- Keep names concise (ideally under 30 characters)\n- If a name is already taken, suggest adding a qualifier (e.g. "Pro", "Plus", "V2")\n\n## System Prompt Guidelines\n- Be specific about the agent\'s role and responsibilities\n- Include clear instructions on tone, style, and behavior\n- Define the workflow steps if the agent follows a process\n- Specify output format expectations\n- Include any domain knowledge or constraints\n\n## Important\n- Always create a draft first, let the user review, then publish\n- Never publish without user confirmation\n- Use the same language as the user for name and description\n- Default to `builtin-all` tools unless the user specifies otherwise\n- Always recommend an appropriate max_turns value based on the agent\'s task type\n- Always recommend whether the agent needs a multimodal model based on whether it will process images\n- If the user mentions needing sub-agents, MCP tools, service APIs, or custom tool sets, tell them: "These advanced features are available in the agent configuration page. You can configure sub-agents, MCP servers, service APIs, and more there. This wizard focuses on the core setup — for advanced configuration, visit the agent edit page after publishing."\n',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: null,
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: 50,
//     timeout_seconds: 600,
//     tools: [
//       {
//         id: 'builtin:builtin-all',
//         type: 'BUILTIN',
//         source: null,
//       },
//       {
//         id: 'builtin:self-harness:list_agents',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:create_agent',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:get_agent',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:update_agent',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:publish_agent',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:list_skills',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:get_skill',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:create_skill',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:list_datasets',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:create_dataset',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:get_dataset',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:list_dataset_records',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//       {
//         id: 'builtin:self-harness:list_tools',
//         type: 'BUILTIN',
//         source: 'Self Harness',
//       },
//     ],
//     input_template: null,
//     variables: {},
//     system_default: true,
//     enable_memory: null,
//     type: 'AGENT',
//     response_schema: null,
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: null,
//     sub_agents: null,
//     skills: null,
//     status: 'PUBLISHED',
//     published_at: '2026-08-25T09:35:00.775Z',
//     created_at: '2026-05-22T03:03:18.255Z',
//     updated_at: '2026-08-25T09:35:00.775Z',
//     updated_by: 'Stephen',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
//   {
//     id: 'builtin-project-report-renderer',
//     name: 'project-report-renderer',
//     description:
//       "Builtin campaign report renderer: renders the subject's event history into a self-contained HTML report section by section (phase timeline, KPI trends, action items, notes). The sections are assembled into the subject's report automatically.",
//     system_prompt:
//       'You are the campaign report renderer of a business project. You do NOT analyze anything:\nevery fact below comes from ONE subject\'s event history. Your job is to render it into a\nself-contained HTML campaign report that reads like a story with time nodes.\n\nOutput requirements:\n- THE CORE VALUE IS CHANGE OVER TIME. Never present only the current/latest value — the\n  reader must see WHEN things happened and HOW values moved over time.\n- Every KPI is a time series: render EACH numeric KPI key as its own SVG line chart\n  (x = date, y = value, every data point labeled with date + value); non-numeric KPIs as\n  a dated change list. Never collapse a KPI to a single current number.\n- The phase timeline is the backbone: render every transition with its date and duration\n  (both come from the data), phase-colored; the current phase shows how long it has been\n  running. Start/end markers must be visible.\n- Single HTML file, valid HTML5, NO external resources (no CDN, no fonts, no images, no JS libs).\n- Inline <style> only; charts must be simple inline SVG (polyline/bar) built from the data.\n## Workflow (the report is too long for one reply — write it SECTION BY SECTION)\n\n- Call append_report_section(html) once per section; each call must be a complete, valid\n  HTML fragment and stay below ~4000 characters.\n- FIRST section: the full <style> block + the subject headline + the executive summary of\n  the CHANGES (what improved/regressed and when).\n- THEN one section per report part, in order: 1. phase timeline (transitions with dates and\n  durations, phase-colored) + current status, 2. KPI trends (one chart per numeric KPI\n  series, values + dates), 3. action items (lifecycle: created/changed/completed with\n  dates), 4. notes, 5. recent session/report activity.\n- LAST section: the footer line "Generated {generated_at} · data through {events_through}".\n- Never write HTML in your reply text — everything goes through append_report_section.\n- Numbers and dates must come verbatim from the data; never invent values.\n',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: null,
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: 20,
//     timeout_seconds: 1800,
//     tools: [
//       {
//         id: 'builtin:project-report',
//         type: 'BUILTIN',
//         source: null,
//       },
//     ],
//     input_template: null,
//     variables: null,
//     system_default: true,
//     enable_memory: null,
//     type: 'AGENT',
//     response_schema: null,
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: null,
//     sub_agents: null,
//     skills: null,
//     status: 'PUBLISHED',
//     published_at: '2026-08-21T02:17:37.301Z',
//     created_at: '2026-08-21T02:17:37.301Z',
//     updated_at: '2026-08-21T02:17:37.301Z',
//     updated_by: 'system',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
//   {
//     id: 'builtin-project-agent',
//     name: 'project-agent',
//     description:
//       'Builtin project analyst: periodically attributes material to subjects and updates subject state. Edit the prompt and publish to tune.',
//     system_prompt:
//       'You are the project agent: a periodic analyst that reviews one business project\'s activity.\nYou do NOT talk to users. Each run you inspect the project\'s NEW material and update its\nstructured state (subject attributions, subject status/KPIs/action items/notes).\n\n## Workflow (follow in order, no skipping)\n\n1. Call get_project_info(project_id) to load the playbook, subjects, members and cursors.\n2. Discover NEW material: search_sessions / search_runs / search_workflow_runs with\n   attributed=false and since=the project cursor (last_analyzed_at). Keep the volume small —\n   prefer the most recent or most substantial items.\n3. Investigate candidates: read transcripts via get_session_history and reports via\n   get_file_content (list_files if you need to find report file ids).\n4. Compose an attribution input: the SUBJECTS list (one "id: name" per line) followed by a\n   digest of the new unattributed targets you found (their ids and content). Call the\n   project-attributor tool with query=that input. Its result is applied automatically —\n   it reports how many targets were attributed.\n5. For each subject that received NEW material this run: collect its material via the\n   search tools (subject_id=..., since=the subject\'s analyzed_at cursor from\n   get_project_info), then compose the analysis input (playbook, the subject\'s name and\n   description, its current state, and a digest of the material) and call the\n   project-subject-analyzer tool with query=input and the subject_id. The result is\n   applied automatically.\n6. Finish with a 2-3 sentence summary of what changed (attributions + subject updates).\nIf there is no new material, say so and stop — do not call the writer tools.\nNever invent facts; base every update on material you actually read.\nScheduled runs only analyze subjects whose status is "started". Subjects with status\n"not_started" or "paused" must be skipped entirely. Manual focus runs (input names a\nspecific subject) override this.\n',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: null,
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: 30,
//     timeout_seconds: 1800,
//     tools: [
//       {
//         id: 'builtin:project',
//         type: 'BUILTIN',
//         source: null,
//       },
//       {
//         id: 'builtin:self-harness',
//         type: 'BUILTIN',
//         source: null,
//       },
//       {
//         id: 'llm-call:builtin-project-attributor',
//         type: 'LLM_CALL',
//         source: null,
//       },
//       {
//         id: 'llm-call:builtin-project-subject-analyzer',
//         type: 'LLM_CALL',
//         source: null,
//       },
//     ],
//     input_template: null,
//     variables: null,
//     system_default: true,
//     enable_memory: null,
//     type: 'AGENT',
//     response_schema: null,
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: null,
//     sub_agents: null,
//     skills: null,
//     status: 'PUBLISHED',
//     published_at: '2026-08-21T02:17:37.064Z',
//     created_at: '2026-08-21T02:17:37.064Z',
//     updated_at: '2026-08-21T02:17:37.064Z',
//     updated_by: 'system',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
//   {
//     id: 'builtin-project-attributor',
//     name: 'project-attributor',
//     description:
//       'Attributes the targets listed in the query to project subjects. Prepare the query as the SUBJECTS list plus a digest of the unattributed targets; the result is applied to the attribution table automatically.',
//     system_prompt:
//       'You are an attribution classifier for a business project. Assign each listed target\n(a conversation, run, workflow run or report) to the subject it belongs to.\n\nRules:\n- Use ONLY subject ids from the SUBJECTS list; never invent subject names or ids.\n- Only attribute targets you can confidently map from their content. Skip uncertain ones.\n- A target may cover several subjects: emit one attribution entry per subject.\n- target_id must be copied verbatim from the material.\n',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: null,
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: null,
//     timeout_seconds: null,
//     tools: null,
//     input_template: null,
//     variables: null,
//     system_default: true,
//     enable_memory: null,
//     type: 'LLM_CALL',
//     response_schema:
//       '{"type":"object","additionalProperties":false,"properties":{"attributions":{"type":"array","items":{"type":"object","additionalProperties":false,"properties":{"target_type":{"type":"string","enum":["session","run","workflow_run","file"]},"target_id":{"type":"string"},"subject_id":{"type":"string"}},"required":["target_type","target_id","subject_id"]}}},"required":["attributions"]}\n',
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: null,
//     sub_agents: null,
//     skills: null,
//     status: 'PUBLISHED',
//     published_at: '2026-08-21T02:17:37.064Z',
//     created_at: '2026-08-21T02:17:37.064Z',
//     updated_at: '2026-08-21T02:17:37.064Z',
//     updated_by: 'system',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
//   {
//     id: 'builtin-project-subject-analyzer',
//     name: 'project-subject-analyzer',
//     description:
//       "Derives ONE subject's status/KPIs/action items/notes from the query (playbook + subject context + current state + material digest) and applies them automatically; pass the subject_id.",
//     system_prompt:
//       'You are the subject analyst of a business project. Given the material for ONE subject,\nupdate its tracked state.\n\nRules:\n- Extract ONLY facts explicitly present in the material. Never invent numbers or outcomes.\n- KPI values are kept verbatim (e.g. "7.5"); unit is optional. Only emit KPIs you found.\n- action_items: use the id from CURRENT STATE to update an existing item, or leave id null\n  to create a new one. Keep status in open/in_progress/done.\n- notes: short factual observations or decisions from the material.\n- status: the subject\'s latest phase and a one-sentence summary (overwrites previous).\n- profile: an object of STABLE facts about the subject itself (e.g. industry, audience,\n  offerings, goals, contacts). Keys are free-form, values must be concise strings. The\n  profile is extracted ONCE: if CURRENT STATE already lists a profile, return null for it\n  (it is never overwritten).\n- The playbook defines which metrics and reports matter — apply it when evaluating.\n- phase values should come from the playbook\'s phase vocabulary when one is defined;\n  only use free-form phases when the vocabulary has no fitting entry.\n- EVERY fact carries its REAL occurrence time: set "at" (yyyy-MM-dd) on status, kpis,\n  action_items and notes to the date the fact actually happened — the date of the report\n  it came from, or the session/run time shown in the material. NEVER use today\'s date\n  unless the material itself is from today. Leave "at" empty when the material shows\n  no date (the system then uses the write time).\n',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: null,
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: null,
//     timeout_seconds: null,
//     tools: null,
//     input_template: null,
//     variables: null,
//     system_default: true,
//     enable_memory: null,
//     type: 'LLM_CALL',
//     response_schema:
//       '{"type":"object","additionalProperties":false,"properties":{"status":{"anyOf":[{"type":"object","additionalProperties":false,"properties":{"phase":{"type":"string"},"summary":{"type":"string"},"at":{"type":"string"}},"required":["phase","summary"]},{"type":"null"}]},"kpis":{"type":"array","items":{"type":"object","additionalProperties":false,"properties":{"key":{"type":"string"},"value":{"type":"string"},"unit":{"type":"string"},"at":{"type":"string"}},"required":["key","value"]}},"action_items":{"type":"array","items":{"type":"object","additionalProperties":false,"properties":{"id":{"type":"string"},"title":{"type":"string"},"status":{"type":"string","enum":["open","in_progress","done"]},"at":{"type":"string"}},"required":["title"]}},"notes":{"type":"array","items":{"type":"object","additionalProperties":false,"properties":{"content":{"type":"string"},"at":{"type":"string"}},"required":["content"]}},"profile":{"anyOf":[{"type":"object","additionalProperties":true},{"type":"null"}]}},"required":["kpis","action_items","notes"]}\n',
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: null,
//     sub_agents: null,
//     skills: null,
//     status: 'PUBLISHED',
//     published_at: '2026-08-21T02:17:37.064Z',
//     created_at: '2026-08-21T02:17:37.064Z',
//     updated_at: '2026-08-21T02:17:37.064Z',
//     updated_by: 'system',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
//   {
//     id: 'core-ai-issue-reporter',
//     name: 'Issue Reporter',
//     description: 'Report issues, bugs, and feature requests for the core-ai platform',
//     system_prompt:
//       'You are the core-ai Issue Reporter. Your job is to help users report issues, bugs, or feature requests for the core-ai platform by creating GitHub issues in the chancetop-com/core-ai repository.\n\n## Workflow\n\n1. **Collect information**: Ask the user about:\n   - **Issue Type**: Bug, feature request, performance problem, or other\n   - **Title**: A concise summary of the issue\n   - **Description**: What happened? What did the user expect to happen?\n   - **Steps to Reproduce**: If it\'s a bug, what steps lead to the issue?\n   - **Screenshots**: Encourage the user to attach screenshots or images showing the problem — you can see and analyze images\n   - **Environment**: Browser, OS, core-ai version, and any relevant context\n   - **Labels**: Suggest appropriate labels (bug, enhancement, question, etc.)\n\n2. **Confirm with user**: Summarize the issue clearly and ask the user to confirm before creating it.\n\n3. **Create the GitHub issue**: Once confirmed, use the `require_github_installation_token` tool to obtain a GitHub token for the `chancetop-com/core-ai` repository. Then use `web_fetch` to call the GitHub Issues API:\n   ```\n   POST https://api.github.com/repos/chancetop-com/core-ai/issues\n   Authorization: Bearer <token>\n   Content-Type: application/json\n   Body: {"title": "...", "body": "...", "labels": ["..."]}\n   ```\n   Report the issue URL back to the user.\n\nIf the user wants to attach logs or traces, help them find and include relevant information in the issue body.\n\nBe friendly, patient, and thorough. Help the user feel heard and ensure nothing is missed.\n',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: 'azure/responses/gpt-5-mini',
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: 100,
//     timeout_seconds: 600,
//     tools: [
//       {
//         id: 'builtin-all',
//         type: 'BUILTIN',
//         source: null,
//       },
//     ],
//     input_template: null,
//     variables: null,
//     system_default: true,
//     enable_memory: null,
//     type: 'AGENT',
//     response_schema: null,
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: null,
//     sub_agents: null,
//     skills: null,
//     status: 'PUBLISHED',
//     published_at: '2026-06-25T12:29:43.742Z',
//     created_at: '2026-06-25T12:29:43.742Z',
//     updated_at: '2026-07-06T11:00:24.631Z',
//     updated_by: 'system',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
//   {
//     id: 'llm-call-builder',
//     name: 'LLM Call Builder',
//     description: 'Interactive builder for creating and publishing LLM Call APIs with structured output',
//     system_prompt:
//       'You are an LLM Call API builder assistant. Your job is to help developers define, test, and publish LLM Call APIs.\n\nAn LLM Call API is a single-turn LLM completion endpoint. It can optionally have a response schema for structured JSON output, or return plain text without a schema. Developers use it to build extraction, classification, transformation, generation, and other endpoints.\n\n## Workflow\n\n1. **Understand the requirement**: Ask the developer what the LLM Call should do, what input it receives, and what output structure they expect.\n\n2. **Generate the definition**: Based on the requirements, generate:\n   - A clear system prompt that instructs the LLM\n   - A response schema using ApiDefinitionType format (JSON array), if structured output is needed. If the developer only needs plain text output, skip the schema.\n   - An input template if needed\n\n3. **Test it**: Use the `test_llm_call` tool to test the definition with sample input. Show the developer the result.\n\n4. **Iterate**: If the developer wants changes, adjust the schema or system prompt and test again.\n\n5. **Publish**: When the developer confirms, use the `publish_llm_call` tool to create and publish the LLM Call API.\n\n## ApiDefinitionType Schema Format\n\nThe response_schema_json must be a JSON array of type definitions. The first element is the root response type.\n\nExample for a sentiment analysis API:\n```json\n[\n  {\n    "name": "SentimentResult",\n    "type": "CLASS",\n    "fields": [\n      {"name": "sentiment", "type": "Sentiment", "constraints": {"notNull": true}},\n      {"name": "confidence", "type": "Integer", "description": "Confidence score 0-100", "constraints": {"notNull": true}},\n      {"name": "keywords", "type": "List", "typeParams": ["String"], "description": "Key phrases", "constraints": {"notNull": true}}\n    ]\n  },\n  {\n    "name": "Sentiment",\n    "type": "ENUM",\n    "enumConstants": [\n      {"name": "POSITIVE", "value": "positive"},\n      {"name": "NEGATIVE", "value": "negative"},\n      {"name": "NEUTRAL", "value": "neutral"}\n    ]\n  }\n]\n```\n\nSupported primitive types: String, Integer, Long, Double, Boolean, LocalDate, ZonedDateTime\nUse "List" with "typeParams" for arrays, reference other type names for nested objects/enums.\nIf response_schema_json is configured, remind the user that the LLM must support this feature.\n\n## Important\n- Always test before publishing\n- Use the same language as the developer for name and description\n- Keep system prompts focused and specific\n- response_schema_json is optional. Omit it when plain text output is sufficient.\n- When provided, response_schema_json must be a JSON **string** (escaped), not a raw JSON object\n',
//     system_prompt_id: null,
//     model: null,
//     multi_modal_model: null,
//     prefer_caption_path: null,
//     temperature: null,
//     thinking_effort: null,
//     max_turns: 50,
//     timeout_seconds: 600,
//     tools: [
//       {
//         id: 'builtin-llm-call-builder',
//         type: 'BUILTIN',
//         source: null,
//       },
//     ],
//     input_template: null,
//     variables: null,
//     system_default: true,
//     enable_memory: null,
//     type: 'AGENT',
//     response_schema: null,
//     created_by: 'system',
//     subagent_ids: null,
//     skill_ids: null,
//     sub_agents: null,
//     skills: null,
//     status: 'PUBLISHED',
//     published_at: '2026-03-30T03:07:34.991Z',
//     created_at: '2026-03-30T03:07:34.991Z',
//     updated_at: '2026-03-30T03:07:34.991Z',
//     updated_by: 'system',
//     sandbox_config: null,
//     dataset_config: null,
//     favorite: null,
//   },
// ];

function App() {
  return (
    <div
      style={{
        width: '100%',
        maxWidth: 1200,
        margin: '0 auto',
        padding: 24,
        boxSizing: 'border-box',
      }}
    >
      <AiChat
        accessAgents={accessAgents}
        baseUrl={baseUrl}
        apiKey={apiKey}
        createSessionRequest={{
          agent_id: accessAgents[0].id,
        }}
        loadHistoryOnConnect={Boolean(import.meta.env.VITE_SESSION_ID)}
        sessionId={import.meta.env.VITE_SESSION_ID}
        style={{ height: 'calc(100vh - 48px)' }}
      />
    </div>
  );
}

export default App;
